import { type NextPage } from "next";
import { Head } from "next/document";
import AuthShowcase from ".";
import { Brand } from "../components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex flex-col items-center gap-2">
          <Brand />
          <AuthShowcase />
        </div>
      </main>
    </div>
  );
};

export default Home;
